default: &default
  adapter: redis
  url: redis://redis:6379/0

development:
  <<: *default
  channel_prefix: bandit_dev

test:
  <<: *default

production:
  <<: *default
  channel_prefix: bandit_prod
