default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: bandit_dev

test:
  <<: *default
  database: bandit_test

production:
  <<: *default
  database: bandit_prod
