version: '3.6'

services:
  postgres:
    image: postgres:11.1
    volumes:
      - ./pgdata/log:/var/log/postgresql
      - ./pgdata/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 54321:5432
  backend:
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    env_file:
      - ./.env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/home/astral/backend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        APP_PATH: ${APP_PATH}
    command: yarn run start
    volumes:
      - ./frontend/node_modules:/usr/band-it/frontend/node_modules
      - ./frontend:/usr/band-it/frontend
    env_file:
      - ./.env
    ports:
      - 8080:8080