version: '3.6'

services:
  postgres:
    image: postgres:11.1
    volumes:
      - /usr/data/volumes/pgdata/etc:/etc/postgresql
      - /usr/data/volumes/pgdata/log:/var/log/postgresql
      - /usr/data/volumes/pgdata/data:/var/lib/postgresql/data
    env_file:
      - ./.env
  backend:
    depends_on:
      - postgres
    build: ./backend
    user: astral
    environment:
    - BUNDLE_PATH=/home/astral/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/home/astral/backend
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    command: yarn run start
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    

